org.gradle.jvmargs=-Xmx4096m -XX:+UseG1GC -XX:G1HeapRegionSize=4m -XX:MaxMetaspaceSize=512m
kotlin.daemon.jvmargs=-Xmx1024m -XX:+UseG1GC
org.gradle.daemon=false
org.gradle.parallel=false
kotlin.incremental=false
android.useAndroidX=true
android.enableJetifier=true
org.gradle.caching=false
org.gradle.workers.max=1

# Enable R8 Full Mode Optimization
android.enableR8.fullMode=true


